config/routes.rb
Rails.application.routes.draw do
  
  get 'homes/index'
  get 'frees/search' => 'frees#search'
  get 'fcomments/create'

  get 'fcomments/destroy'
  
  get '/find_room' => 'room#find_room' 

  devise_for :users
  resources :conversations, only: [:create] do
   member do
    post :close
   end
  resources :messages, only: [:create]
  end
  
  root 'home#index'
  
  get 'enrollprofiles/index' => 'enrollprofiles#index'
  post 'enrollprofiles/create' => 'enrollprofiles#create'
 
  get 'enrollprofiles/show' => 'enrollprofiles#show'
  post 'enrollprofiles/update' => 'enrollprofiles#update'
  
  get 'home/index'
  get 'home/mypage' => 'home#mypage'
  get 'home/intro' => 'home#intro'
  get '/room/seoul' =>'room#seoul'
  get '/room/jeolla' =>'room#jeolla'
  get '/room/gyeongsang' =>'room#gyeongsang'
  get '/room/jeju' =>'room#jeju'
  get '/room/chungcheong' =>'room#chungcheong'
  get '/room/gangwon' =>'room#gangwon'
  get '/room/gyeonggi' =>'room#gyeonggi'
  get '/room/siteview' => 'room#siteview'
  get '/search_profile' =>'people#search_profile'
  
  get 'people/base' => 'people#base'
  get 'people/drum' => 'people#drum'
  get 'people/guitar' => 'people#guitar'
  get 'people/keyboard' => 'people#keyboard'
  get 'people/etc' => 'people#etc'
  get 'people/vocal' => 'people#vocal'
  get '/homes/index'
  get '/conversations/_conversation' => 'conversations#_conversation'
  get 'messages/_message'=>'messages#_message'
  
  get 'people/email_form' =>'people#email_form'
  get 'people/email_send' =>'people#email_send'
  post 'email/send' =>'email#send'

 

  resources :works do
    collection do
      get :search
    end
  end
  
  get 'works/search' => 'works#search'
  post '/wcomments' => 'wcomments#create'
  delete '/wcomments/:id' => 'wcomments#destroy'
  post 'work/:work_id/wlike' => 'works#wlike_toggle'
  
  resources :frees do
    resources :fcomments, only: [:create, :destroy]
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    has_many :messages, dependent: :destroy

    belongs_to :sender, foreign_key: :sender_id, class_name: User

    belongs_to :recipient, foreign_key: :recipient_id, class_name: User

    

    validates :sender_id, uniqueness: { scope: :recipient_id }

    

    scope :between, -> (sender_id, recipient_id) do

        where(sender_id: sender_id, recipient_id: recipient_id).or(

          where(sender_id: recipient_id, recipient_id: sender_id)

        )

    end

    

    def self.get(sender_id, recipient_id)

        conversation = between(sender_id, recipient_id).first

        return conversation if conversation.present?

        create(sender_id: sender_id, recipient_id: recipient_id)

    end

    

    def opposed_user(user)

        user == recipient ? sender : recipient

    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    def create

        @conversation = Conversation.get(current_user.id, params[:user_id])

        add_to_conversations unless conversated?

        respond_to do |format|

            format.js

        end

    end

    

    def close

        @conversation = Conversation.find(params[:id])

        session[:conversations].delete(@conversation.id)

        

        respond_to do |format|

            format.js

        end

    end

    

    private

    

    def add_to_conversations

        session[:conversations] ||= []

        session[:conversations] << @conversation.id

    end

    

    def conversated?

        session[:conversations].include?(@conversation.id)

    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<li>

  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">

    <div class="panel-heading">

      <%= link_to conversation.opposed_user(user).email, '', class: 'toggle-window' %>

      <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>

    </div>

 

    <div class="panel-body" style="display: none;">

      <div class="messages-list">

        <ul>

          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>

        </ul>

      </div>

      <%= form_for [conversation, conversation.messages.new], remote: true do |f| %>

        <%= f.hidden_field :user_id, value: user.id %>

        <%= f.text_area :body, class: "form-control" %>

        <%= f.submit "전송", class: "btn btn-success" %>

      <% end %>

    </div>

  </div>

</li>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/conversation_content.html.erb
<% messages.each do |message| %>

    <%= render message, user: user %>

<% end %>

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');

var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

 

if (conversation.length !== 1) {

  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");

  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

}

 

conversation.find('.panel-body').show();

 

var messages_list = conversation.find('.messages-list');

var height = messages_list[0].scrollHeight;

messages_list.scrollTop(height);