config/routes.rb
Rails.application.routes.draw do
  
  get 'homes/index'
  get 'frees/search' => 'frees#search'
  get 'fcomments/create'

  get 'fcomments/destroy'
  
  get '/find_room' => 'room#find_room' 

  devise_for :users
  resources :conversations, only: [:create] do
   member do
    post :close
   end
  resources :messages, only: [:create]
  end
  
  root 'home#index'
  
  get 'enrollprofiles/index' => 'enrollprofiles#index'
  post 'enrollprofiles/create' => 'enrollprofiles#create'
 
  get 'enrollprofiles/show' => 'enrollprofiles#show'
  post 'enrollprofiles/update' => 'enrollprofiles#update'
  
  get 'home/index'
  get 'home/mypage' => 'home#mypage'
  get 'home/intro' => 'home#intro'
  get '/room/seoul' =>'room#seoul'
  get '/room/jeolla' =>'room#jeolla'
  get '/room/gyeongsang' =>'room#gyeongsang'
  get '/room/jeju' =>'room#jeju'
  get '/room/chungcheong' =>'room#chungcheong'
  get '/room/gangwon' =>'room#gangwon'
  get '/room/gyeonggi' =>'room#gyeonggi'
  get '/room/siteview' => 'room#siteview'
  get '/search_profile' =>'people#search_profile'
  
  get 'people/base' => 'people#base'
  get 'people/drum' => 'people#drum'
  get 'people/guitar' => 'people#guitar'
  get 'people/keyboard' => 'people#keyboard'
  get 'people/etc' => 'people#etc'
  get 'people/vocal' => 'people#vocal'
  get '/homes/index'
  get '/conversations/_conversation' => 'conversations#_conversation'
  get 'messages/_message'=>'messages#_message'
  
  get 'people/email_form' =>'people#email_form'
  get 'people/email_send' =>'people#email_send'
  post 'email/send' =>'email#send'

 

  resources :works do
    collection do
      get :search
    end
  end
  
  get 'works/search' => 'works#search'
  post '/wcomments' => 'wcomments#create'
  delete '/wcomments/:id' => 'wcomments#destroy'
  post 'work/:work_id/wlike' => 'works#wlike_toggle'
  
  resources :frees do
    resources :fcomments, only: [:create, :destroy]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
    def intro
    end
    
    def mypage
        @users = User.all
        @extras = Extra.all
        @a = 1
    end
    

    # def check_user_login
    #     if @user != User.find(params[:id])
    #         redirect_to root_url
    #     end
    # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    session[:conversations] ||= []

 

    @users = User.all.where.not(id: current_user)

    @conversations = Conversation.includes(:recipient, :messages)
                     .find(session[:conversations])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <section>
        
        <div class="imgcontainer">
            <div class="box box1">
                <div class="back back1"><img src="/menu1_back.png" /></div>
                <% if user_signed_in? %>
                <div class="front front1"><a href = "/works"><img src="/menu1_front.png" /></a></div>
                <% else %>
                <div class="front front1"><a href = "/users/sign_in" data-confirm = "로그인해주세요"><img src="/menu1_front.png" /></a></div>
                <% end %>
            </div>
            <div class="box box2">
                <div class="back back2"><img src="/menu2_back.png" /></div>
                <div class="front front2"><a href = "/find_room"><img src="/menu2_front.png" /></a></div>
            </div>
            <div class="box box3">
                <div class="back back3"><img src="/menu3_back.png" /></div>
                <div class="front front3"><a href = "/frees"><img src="/menu3_front.png" /></a></div>
            </div>
            <div class="box box4">
                <div class="back back4"><img src="/menu4_back.png" /></div>
                <% if user_signed_in? %>
                <div class="front front4"><a href = "/home/index"><img src="/menu4_front.png" /></a></div>
                <% else %>
                <div class="front front4"><a href = "/users/sign_up"><img src="/menu4_front.png" /></a></div>
                <% end %>
            </div>
        </div>
        
        <footer>
            <div class="introduce"><img src="/main_page.png" /></div>
        </footer>
        
        <div class='copyright'>
            <p>Copyright &copy; 2018 Seoul Women's University<br><%=link_to '김태영 | 백승민 | 윤현조 | 정세영 | 최은희 | 한주희',home_intro_path%></p>
        </div>
            
    </section>
</body>
</html>

app/views/home/intro.html.erb
<!DOCTYPE html>
<html>
<head>
    <style>
        .imgcontainer {
            width:1200px;
            margin:0 auto;
        }
        .box img {
            width:300px;
        }
        .first {
            position:absolute;
            top:0;
            left:0px;
        }
        .back1 {
            position:absolute;
            top:0;
            left:300px;
        }
        .front1 {
            position:absolute;
            top:0;
            left:300px;
        }
        .back2 {
            position:absolute;
            top:0;
            left:600px;
        }
        .front2 {
            position:absolute;
            top:0;
            left:600px;
        }
        .back3 {
            position:absolute;
            top:0;
            left:900px;
        }
        .front3 {
            position:absolute;
            top:0;
            left:900px;
        }
        .back4 {
            position:absolute;
            top:299.17px;
            left:0;
        }
        .front4 {
            position:absolute;
            top:299.17px;
            left:0;
        }
        .back5 {
            position:absolute;
            top:299.17px;
            left:300px;
        }
        .front5 {
            position:absolute;
            top:299.17px;
            left:300px;
        }
        .back6 {
            position:absolute;
            top:299.17px;
            left:600px;
        }
        .front6 {
            position:absolute;
            top:299.17px;
            left:600px;
        }
        .last {
            position:absolute;
            top:299.17px;
            left:900px;
        }
        .front:hover {
            opacity:0;
            transition:opacity 0.4s ease;
        }
        .container1 {
            margin-top:50px;
            margin-bottom:40px;
        }
        .copyright2 {
            margin-top:700px;
            text-align:center;
            margin-bottom:80px;
        }
        /*게시판 제목*/
        .place {
            margin-top:40px;
        }
        .board-container {
            margin:0 auto;
            display:grid;
            width:1200px;
            grid-template-columns:10px auto;
            grid-template-rows:50px 30px;
        }
        .line {
            /*border:thin solid black;*/
        }
        .line1 {
            grid-row:span 2;
            background-color:#666;
        }
        .line3, .line4 {
            padding-left:20px;
        }
        .line3 {
            font-size:42px;
            line-height:50px;
        }
        .line4 {
            font-size:18px;
            line-height:30px;
        }
    </style>
</head>
<body>
<section>
    <div class="place">
    <div class="board-container">
        <div class="line line1"></div>
        <div class="line line3">개발자 소개</div>
        <div class="line line4">Introduction of Developers</div>
    </div>
    </div>
    
    <div class="container1">
        <div class="imgcontainer">
            <div class="box">
                <div class="first"><img src="/0-03.png"></div>
            </div>
            <div class="box box1">
                <div class="back back1"><img src="/2-03.png" /></div>
                <div class="front front1"><img src="/1-03.png" /></div>
            </div>
            <div class="box box2">
                <div class="back back2"><img src="/4-03.png" /></div>
                <div class="front front2"><img src="/3-03.png" /></div>
            </div>
            <div class="box box3">
                <div class="back back3"><img src="/6-03.png" /></div>
                <div class="front front3"><img src="/5-03.png" /></div>
            </div>
        </div>
        
        <div class="imgcontainer">
            <div class="box box1">
                <div class="back back4"><img src="/8-03.png" /></div>
                <div class="front front4"><img src="/7-03.png" /></div>
            </div>
            <div class="box box2">
                <div class="back back5"><img src="/10-03.png" /></div>
                <div class="front front5"><img src="/9-03.png" /></div>
            </div>
            <div class="box box3">
                <div class="back back6"><img src="/12-03.png" /></div>
                <div class="front front6"><img src="/11-03.png" /></div>
            </div>
            <div class="box">
                <div class="last"><img src="/13-03.png"/></div>
            </div>
        </div>
    </div>
        
        
    <div class="copyright2">
        <p>Copyright &copy; 2018 Seoul Women's University<br>멋쟁이사자처럼 LIKELION HACKATHON</p>
    </div>
</section>

</body>
</html>

app/views/home/mypage.html.erb
<html>
    <head>
        <meta charset="utf-8" />
        <!--<link rel="stylesheet" href="css/style.css" />-->
        <style>
            .container {
                margin-top:150px;
                margin-bottom:40px;
            }
            .portfolio-item {
                width:100%;
            }
            
            .navbar {
                width:100%;
            }
            
            .form-inline {
                width:400px;
                margin:0 auto;
            }
            
            .formContain a {
                margin:0 20px;
            }
            
            .row {
                display: inline-block;
                width: 400px;
                margin: 1% 2%;
                border-radius: 10px;
                border: 1px solid #BDBDBD;
                
            }
            .portfolio-item {
                margin-bottom: 30px;
                
            }
        </style>
    </head>
<body>
<div class="container">

<center><h3>My Page</h3><br>

<center>
 

 <%@users.each do |x| %>
 <%if x.id == current_user.id%>
 
 <div class="row">
        <div class="portfolio-item">
          <div class="card h-100">
            <%@extras.each do |e| %>
            <%if e.user_id == x.id %>
            <%@a=0%>
            <%if e.avatar.exists?%>
                <%= image_tag e.avatar.url(:medium) %></a>  <!--이미지-->
            <%else%>
                <img style="width:390px;height:500px;" src="/default.png">
            <%end%>
            <%end%>
            <%end%>
            
            <%if @a==1%>
            <img style="width:390px;height:500px;" src="/default.png">
            <%end%>
            <% @a=1 %>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">악기 : <%=x.instrument%></a> <!--악기-->
              </h4>
              <p class="card-text">닉네임 : <%=x.nickname%></p> <!--닉네임-->
              <p class="card-text">사는 곳 : <%=x.region%></p> <!--닉네임-->
              
              <%@extras.each do |e| %>
              <%if e.user_id == x.id %>
              <p class="card-text">소개글 : <%=e.introduce%></p>
              <%end%>
              <%end%>
              
        
            </div>
          </div>
        </div>
  
  </div>
  <%end%>
  <%end%>
  
  <% if user_signed_in? %>
        <%unless current_user.extras.any? %>
        <p><%=link_to '프로필 등록하기', enrollprofiles_index_path%></p><br><br>
        <%else%>
        <p><%=link_to '프로필 수정하기', enrollprofiles_show_path%></p><br><br>
        <%end%>
        <%end%>
</center>

</div>

</body>
</html>