config/routes.rb
Rails.application.routes.draw do
  
  get 'homes/index'
  get 'frees/search' => 'frees#search'
  get 'fcomments/create'

  get 'fcomments/destroy'
  
  get '/find_room' => 'room#find_room' 

  devise_for :users
  resources :conversations, only: [:create] do
   member do
    post :close
   end
  resources :messages, only: [:create]
  end
  
  root 'home#index'
  
  get 'enrollprofiles/index' => 'enrollprofiles#index'
  post 'enrollprofiles/create' => 'enrollprofiles#create'
 
  get 'enrollprofiles/show' => 'enrollprofiles#show'
  post 'enrollprofiles/update' => 'enrollprofiles#update'
  
  get 'home/index'
  get 'home/mypage' => 'home#mypage'
  get 'home/intro' => 'home#intro'
  get '/room/seoul' =>'room#seoul'
  get '/room/jeolla' =>'room#jeolla'
  get '/room/gyeongsang' =>'room#gyeongsang'
  get '/room/jeju' =>'room#jeju'
  get '/room/chungcheong' =>'room#chungcheong'
  get '/room/gangwon' =>'room#gangwon'
  get '/room/gyeonggi' =>'room#gyeonggi'
  get '/room/siteview' => 'room#siteview'
  get '/search_profile' =>'people#search_profile'
  
  get 'people/base' => 'people#base'
  get 'people/drum' => 'people#drum'
  get 'people/guitar' => 'people#guitar'
  get 'people/keyboard' => 'people#keyboard'
  get 'people/etc' => 'people#etc'
  get 'people/vocal' => 'people#vocal'
  get '/homes/index'
  get '/conversations/_conversation' => 'conversations#_conversation'
  get 'messages/_message'=>'messages#_message'
  
  get 'people/email_form' =>'people#email_form'
  get 'people/email_send' =>'people#email_send'
  post 'email/send' =>'email#send'

 

  resources :works do
    collection do
      get :search
    end
  end
  
  get 'works/search' => 'works#search'
  post '/wcomments' => 'wcomments#create'
  delete '/wcomments/:id' => 'wcomments#destroy'
  post 'work/:work_id/wlike' => 'works#wlike_toggle'
  
  resources :frees do
    resources :fcomments, only: [:create, :destroy]
  end

end

app/models/free.rb
class Free < ActiveRecord::Base
  #관리자권한부여
  resourcify
    
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /^image\/(jpeg|png|gif|tiff)$/

  validates_attachment_size :avatar, :in => 0..10.megabytes    
    
  belongs_to :user
  has_many :fcomments
  has_many :impressions, :as=>:impressionable
 
   def impression_count
       impressions.size
   end
 
   def unique_impression_count
       # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
       # so getting keys from the hash and calculating the number of keys
       impressions.group(:ip_address).size.keys.length #TESTED
   end
   
   searchable do
    text :title, :default_boost => 2 #제목
    text :content # 내용
  end
   
end

app/controllers/frees_controller.rb
class FreesController < ApplicationController
   load_and_authorize_resource
  # before_action :set_free, only: [:show, :edit, :update, :destroy]
  # before_action :is_writer?, only: [:edit, :update, :destroy]
  before_action :log_impression, :only=> [:show]
  
  # GET /frees
  # GET /frees.json
  def index
    @notis = Free.all
    @frees = Free.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end
  
  def search
    @notis = Free.all
    @frees = Free.search do
        keywords params[:search]
    end.results
    
    respond_to do |format|
    format.html {render :action => "index"}
    format.xml {render :xml => @posts}
    end
  end
  
  # GET /frees/1
  # GET /frees/1.json
  def show
    @fcomment = Fcomment.new
    @fcomment = @free.fcomments
  end

  # GET /frees/new
  def new
    @free = Free.new
  end

  # GET /frees/1/edit
  def edit
  end

  # POST /frees
  # POST /frees.json
  def create
    @free = Free.new(free_params)
    respond_to do |format|
      if @free.save
        format.html { redirect_to @free, notice: 'Free was successfully created.' }
        format.json { render :show, status: :created, location: @free }
      else
        format.html { render :new }
        format.json { render json: @free.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frees/1
  # PATCH/PUT /frees/1.json
  def update
    respond_to do |format|
      if @free.update(free_params)
        format.html { redirect_to @free, notice: 'Free was successfully updated.' }
        format.json { render :show, status: :ok, location: @free }
      else
        format.html { render :edit }
        format.json { render json: @free.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frees/1
  # DELETE /frees/1.json
  def destroy
    @free.destroy
    respond_to do |format|
      format.html { redirect_to frees_url, notice: 'Free was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def log_impression
    if user_signed_in?
      @hit_post = Free.find(params[:id])
      # this assumes you have a current_user method in your authentication system
      @hit_post.impressions.create(ip_address: request.remote_ip,user_id:current_user.id)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_free
      @free = Free.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def free_params
      # if user_signed_in?
        params[:free][:user_id] = current_user.id
        params.require(:free).permit(:title, :content, :user_id, :nick, :notice, :avatar)
      # end
    end
    
    def is_writer?
      redirect_to @free unless @free.user == current_user
    end
    
end

app/helpers/frees_helper.rb
module FreesHelper
end

app/views/frees/_form.html.erb
<%= form_for(@free, :html => { :multipart => true }) do |f| %>
  <% if @free.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@free.errors.count, "error") %> prohibited this free from being saved:</h2>

      <ul>
      <% @free.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
  <% if current_user.has_role? :admin %>
    <font color="red">공지사항</font><br/>
    <%= f.check_box :notice, id: :free_notice %>
  <% end %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
      <%= f.file_field :avatar %>
  </div>
  <div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :nick, value: current_user.nickname%>
    <!--userid 보내기-->
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frees/edit.html.erb
<html>
    <head>
        <meta charset="utf-8" />
        <!--<link rel="stylesheet" href="css/style.css" />-->
        <style>
            .container {
                margin-top:190px;
            }
        </style>
    </head>
<body>

<div class="container">
<h1>Editing Free</h1>

<%= render 'form' %>

<%= link_to 'Show', @free %> |
<%= link_to 'Back', frees_path %>
</div>
</body>
</html>

app/views/frees/etc.html.erb
<html>
    <head>
        <meta charset="utf-8" />
        <!--<link rel="stylesheet" href="css/style.css" />-->
        <style>
            .container {
                margin-top:190px;
            }
        </style>
    </head>
<body>
<div class="container">
    


</div>    
</body>
</html>

app/views/frees/index.html.erb
<html>
    <head>
        <meta charset="utf-8" />
        <title>html_lecture_</title>
        <!--<link rel="stylesheet" href="css/style.css" />-->
        <style>
            .container {
                margin-top:150px;
                margin-bottom:40px;
            }
            
            .content {
              width:900px;
              margin:0 auto;
            }
            
            .table {
              margin:5px;
            }
        </style>
    </head>
<body>

<div class="container">
  <div class="place">
    <div class="board-container">
        <div class="line line1"></div>
        <div class="line line3">커뮤니티</div>
        <div class="line line4">Community</div>
    </div>
  </div>
<div class="content">
  <p id="notice"><%= notice %></p>
  
  <table class="table">
    <thead>
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
    </thead>
  
    <tbody>
      <% @notis.each do |free| %>
        <% if free.notice == true %>
          <tr>
          <td><strong>공지</strong></td>
          <td><a href ='/frees/<%=free.id%>'><%= free.title %></a></td>
          <td><%= free.nick%></td>
          <td><%= free.updated_at.strftime('%F') %></td>
          <td><%= "#{free.unique_impression_count}" %>
          </tr>
        <% end %>
      <% end %>    
      
      <% @frees.each do |free| %>
        <tr>
          <td><%=free.id%></td>
          <%#if user_signed_in? %>
          <td><a href ='/frees/<%=free.id%>'><%= free.title %></a></td>
          <%#else%>
          <!--<td><a href ='/users/sign_in' data-confirm = "로그인해주세요"><%#= free.title %></a></td>-->
          <%#end%>
          <td><%= free.nick%></td>
          <td><%= free.updated_at.strftime('%F') %></td>
          <td><%= "#{free.unique_impression_count}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= will_paginate @frees, :previous_label => '이전', :next_label => '다음' %>
  <%if user_signed_in?%>
    <%= link_to '글쓰기', new_free_path %>
  <%end%>
  <%= form_tag frees_search_path, :method => :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "검색", :name => nil %>
  <% end %>
  
</div>
</div>

</body>
</html>

app/views/frees/new.html.erb
<html>
    <head>
        <meta charset="utf-8" />
        <title>html_lecture_</title>
        <!--<link rel="stylesheet" href="css/style.css" />-->
        <style>
            .container {
                margin-top:140px;
            }
            
            .content {
                width:200px;
                margin:0 auto;
            }
            
            /*.table {*/
            /*    margin:5px;*/
            /*}*/
        </style>
    </head>
<body>

<div class="container">
<div class="content">
    
    <h1>New Free</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Back', frees_path %>
    
</div>
</div>
</body>
</html>

app/views/frees/show.html.erb
<html>
    <head>
        <meta charset="utf-8" />
        <!--<link rel="stylesheet" href="css/style.css" />-->
        <style>
            .container {
                margin-top:190px;
            }
        </style>
    </head>
<body>

<div class="container">
<p id="notice"><%= notice %></p>

<div class="table">
  <strong>Title:</strong>
  <%= @free.title %>
</div>

<div class="table">
  <strong>Content:</strong>
  <%= @free.content %><br>
  <% if @free.avatar.exists? %>
    <%= image_tag @free.avatar.url %>
  <% end%>
</div>
<div>
<%if user_signed_in?%>
  <%=form_for(Fcomment.new, url: free_fcomments_path(@free.id)) do |c| %>
    <%=c.label :fcontent, '댓글'%>
    <%=c.text_field :fcontent%>
    <%=c.hidden_field :user_id, value: current_user.id %>
    <%=c.hidden_field :nick, value: current_user.nickname %>
    <%=c.submit '작성'%>
<%end%>
<%else%>
  <%=link_to '댓글을 다시려면 로그인해주세요!', new_user_session_path%>
<%end%>
</div>

<br><br>
<div class="table">
<%@free.fcomments.each do |comment|%>
  <strong><%=comment.nick%></strong>
  <%=comment.updated_at.strftime('%F  %H:%M')%><br>
  <%=comment.fcontent%> 
  <%if user_signed_in?%>
    <%if (current_user.has_role? :admin)||(comment.user == current_user) %>
      <%=link_to '[삭제]', free_fcomment_path(@free.id, comment.id), method: 'delete'%>
    <%end%>
  <%end%>
</div>
<br>
<%end%>
<%if user_signed_in?%>
  <%if (current_user.has_role? :admin)||(@free.user == current_user) %>
    <%= link_to '수정', edit_free_path(@free) %> |
    <%= link_to '삭제', free_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%end%>
<%end%>
<%# else %>
  <%# link_to '로그인해주세요!', new_user_session_path%>
<%# end %>
<%= link_to '목록', frees_path %>
</body>
</html>