config/routes.rb
Rails.application.routes.draw do
  
  get 'homes/index'
  get 'frees/search' => 'frees#search'
  get 'fcomments/create'

  get 'fcomments/destroy'
  
  get '/find_room' => 'room#find_room' 

  devise_for :users
  resources :conversations, only: [:create] do
   member do
    post :close
   end
  resources :messages, only: [:create]
  end
  
  root 'home#index'
  
  get 'enrollprofiles/index' => 'enrollprofiles#index'
  post 'enrollprofiles/create' => 'enrollprofiles#create'
 
  get 'enrollprofiles/show' => 'enrollprofiles#show'
  post 'enrollprofiles/update' => 'enrollprofiles#update'
  
  get 'home/index'
  get 'home/mypage' => 'home#mypage'
  get 'home/intro' => 'home#intro'
  get '/room/seoul' =>'room#seoul'
  get '/room/jeolla' =>'room#jeolla'
  get '/room/gyeongsang' =>'room#gyeongsang'
  get '/room/jeju' =>'room#jeju'
  get '/room/chungcheong' =>'room#chungcheong'
  get '/room/gangwon' =>'room#gangwon'
  get '/room/gyeonggi' =>'room#gyeonggi'
  get '/room/siteview' => 'room#siteview'
  get '/search_profile' =>'people#search_profile'
  
  get 'people/base' => 'people#base'
  get 'people/drum' => 'people#drum'
  get 'people/guitar' => 'people#guitar'
  get 'people/keyboard' => 'people#keyboard'
  get 'people/etc' => 'people#etc'
  get 'people/vocal' => 'people#vocal'
  get '/homes/index'
  get '/conversations/_conversation' => 'conversations#_conversation'
  get 'messages/_message'=>'messages#_message'
  
  get 'people/email_form' =>'people#email_form'
  get 'people/email_send' =>'people#email_send'
  post 'email/send' =>'email#send'

 

  resources :works do
    collection do
      get :search
    end
  end
  
  get 'works/search' => 'works#search'
  post '/wcomments' => 'wcomments#create'
  delete '/wcomments/:id' => 'wcomments#destroy'
  post 'work/:work_id/wlike' => 'works#wlike_toggle'
  
  resources :frees do
    resources :fcomments, only: [:create, :destroy]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    # 주석처리 해제
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else 
      # can :read, create :all
      can [:index, :show, :new, :create, :search], Work
      can [:edit, :update, :destroy], Work, user_id:user.id
      can [:create], Wcomment
      can [:destroy], Wcomment, user_id: user.id
      can [:wlike_toggle], Work
      can [:index, :show, :new, :create, :search], Free
      can [:edit, :update, :destroy], Free, user_id:user.id
      can [:create], Fcomment
      can [:destroy], Fcomment, user_id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    has_many :messages, dependent: :destroy

    belongs_to :sender, foreign_key: :sender_id, class_name: User

    belongs_to :recipient, foreign_key: :recipient_id, class_name: User

    

    validates :sender_id, uniqueness: { scope: :recipient_id }

    

    scope :between, -> (sender_id, recipient_id) do

        where(sender_id: sender_id, recipient_id: recipient_id).or(

          where(sender_id: recipient_id, recipient_id: sender_id)

        )

    end

    

    def self.get(sender_id, recipient_id)

        conversation = between(sender_id, recipient_id).first

        return conversation if conversation.present?

        create(sender_id: sender_id, recipient_id: recipient_id)

    end

    

    def opposed_user(user)

        user == recipient ? sender : recipient

    end
end

app/models/extra.rb
class Extra < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "390x500>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /^image\/(jpeg|png|gif|tiff)$/
  belongs_to :user
end

app/models/fcomment.rb
class Fcomment < ActiveRecord::Base
  #관리자권한부여
  resourcify
  
  belongs_to :user
  belongs_to :free
end

app/models/free.rb
class Free < ActiveRecord::Base
  #관리자권한부여
  resourcify
    
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /^image\/(jpeg|png|gif|tiff)$/

  validates_attachment_size :avatar, :in => 0..10.megabytes    
    
  belongs_to :user
  has_many :fcomments
  has_many :impressions, :as=>:impressionable
 
   def impression_count
       impressions.size
   end
 
   def unique_impression_count
       # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
       # so getting keys from the hash and calculating the number of keys
       impressions.group(:ip_address).size.keys.length #TESTED
   end
   
   searchable do
    text :title, :default_boost => 2 #제목
    text :content # 내용
  end
   
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #권한부여추가(student라는 역할부여)
  after_create :assign_default_role
  def assign_default_role
    add_role(:student)
  end
  rolify
  has_many :works
  has_many :wcomments
  has_many :frees
  has_many :fcomments
  has_many :wlikes
  has_many :extras
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save {self.email = email.downcase}                                     #이메일을 저장하기 전, 주소를 소문자로 변환
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i        #정규식을 이용해 이메일 형식을 지정
  validates :name, presence: true, length: {maximum: 15}                        #이름과 이메일이 반드시 존재하고 15,255자를 넘지 않게하는 유효성검사
  validates :email, presence: true, length: {maximum: 255},                     #validates (존재를 확인), presence(오직 하나만 존재),
          format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}   #uniqueness(이메일소문자)
  validates :nickname, presence: true, length: {maximum: 15}
  
  def is_wlike?(work)
    Wlike.find_by(user_id: self.id, work_id: work.id).present?
  end
end

app/models/view.rb
class View < ActiveRecord::Base
end

app/models/wcomment.rb
class Wcomment < ActiveRecord::Base
  resourcify
  
  belongs_to :work
  belongs_to :user
end

app/models/wlike.rb
class Wlike < ActiveRecord::Base
  belongs_to :work
  belongs_to :user
end

app/models/work.rb
class Work < ActiveRecord::Base
    #관리자권한부여
    resourcify
    
    validates_presence_of :wtitle, :winstrument, :wregion, :wmusic
    searchable do
        text :wtitle
        text :winstrument
        text :wregion
        text :wmusic
    end
    
    belongs_to :user
    has_many :wcomments
    has_many :wlikes
   
    validates :user, presence: true
    self.per_page = 10
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/frees_helper.rb
module FreesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music Together</title>
  <link rel="shortcut icon" href="/main_logo.ico">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
  
  <style>
    a:hover {
      color:#222;
      text-decoration:none!important;
    }
  </style>
  
  <script type="text/javascripts" src="custom.js"></script>

</head>

<body>
  
  <div class="wrap">
    
    <div class="logContain">
      <ul class="logmenu">
        <% if user_signed_in? %>
          <li class="bar"></li>
          <li><a href="/home/mypage">마이페이지</a></li>
          <li class="bar"></li>
          <li><%= link_to '로그아웃', destroy_user_session_path %></li>
          <li class="bar"></li>
          <li class="user_welcome"><%= current_user.nickname %>님 환영합니다.</li>
        <% else %>
          <li class="bar"></li>
          <li><%=link_to '회원가입', new_user_registration_path%></li>
          <li class="bar"></li>
          <li><%=link_to '로그인', new_user_session_path%></li>
          <li class="bar"></li>
        <% end %>
      </ul>
    </div>
    
    <!-- 라우팅 추가는 <a>태그에 대체해 주세요 -->
    
    <div class="menuContain" id="menuContainer">
        <div class="menuwrap">
        <div class="menu">
            <a href='/home/index'><img class="topImg" src="/main_logo.png" /></a>
            <ul>
              <% if user_signed_in? %>
                <li><p><a class="menu1"><%=link_to '연주자찾기', works_path%></a></p></li>
                <li><p><a href="/search_profile" class="menu1">프로필</a></p></li>
                <li><p><a href="/find_room" class="menu1">합주실찾기</a></p></li>
                <li><p><a class="menu1"><%=link_to '커뮤니티', frees_path %></a></p></li>
              <% else %>
                <li><p><a class="menu1"><%=link_to '연주자찾기', user_session_path, method: :POST, data: { confirm: "로그인해주세요." } %></a></p></li>
                <li><p><a class="menu1"><%=link_to '프로필', user_session_path, method: :POST, data: { confirm: "로그인해주세요." } %></a></p></li>
                <li><p><a class="menu1"><%=link_to '연습실찾기', find_room_path %></a></p></li>
                <li><p><a class="menu1"><%=link_to '커뮤니티', frees_path %></a></p></li>
              <% end %>
            </ul>
        </div>
        </div>
    </div>
    
  </div>
    <!--<div class="container">-->
      <%= yield %>  
    </div>
    
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

</body>
</html>